### ISSUE TITLE
Wrong entity stored in form?

### ISSUE THREAD

**Issue by Brice1827** [yii2-extensions/dynamicform#1]
Hello,
in the form example it's seems that instead of:
`<?= Html::submitButton($modelAddress->isNewRecord ? 'Create' : 'Update', ['class' => 'btn btn-primary']) ?>`
it should be:
`<?= Html::submitButton($modelCustomer->isNewRecord ? 'Create' : 'Update', ['class' => 'btn btn-primary']) ?>`

**Comment by mtangoo** [comment]
Thanks @Brice1827. 
It is fixed now
