### ISSUE TITLE
Primary key may not be called "id"

### ISSUE THREAD

**Issue by Brice1827** [yii2-extensions/dynamicform#2]
Especially on existing databases, some primary keys are not called id. 
createMultiple function could take a third parameter to indicates primary key, with default value "id".

**Comment by terabytesoftw** [comment]
You have time for a PR.

**Comment by Brice1827** [comment]
I will try

**Comment by Brice1827** [comment]
I can't git pull: "ERROR: Permission to yii2-extensions/dynamicform.git denied to Brice1827". I'm not very familiar to github, may i nedd some particular rights?

**Comment by mtangoo** [comment]
PR https://github.com/yii2-extensions/dynamicform/pull/3

**Comment by mtangoo** [comment]
Since this is a mojor issue for people with non `id` PK, I have made release 1.0.1
